<?php
// Load Dolibarr environment
$res = 0;
// Try main.inc.php into web root known defined into CONTEXT_DOCUMENT_ROOT (not always defined)
if (!$res && !empty($_SERVER["CONTEXT_DOCUMENT_ROOT"])) {
	$res = @include $_SERVER["CONTEXT_DOCUMENT_ROOT"]."/main.inc.php";
}
// Try main.inc.php into web root detected using web root calculated from SCRIPT_FILENAME
$tmp = empty($_SERVER['SCRIPT_FILENAME']) ? '' : $_SERVER['SCRIPT_FILENAME']; $tmp2 = realpath(__FILE__); $i = strlen($tmp) - 1; $j = strlen($tmp2) - 1;
while ($i > 0 && $j > 0 && isset($tmp[$i]) && isset($tmp2[$j]) && $tmp[$i] == $tmp2[$j]) {
	$i--;
	$j--;
}
if (!$res && $i > 0 && file_exists(substr($tmp, 0, ($i + 1))."/main.inc.php")) {
	$res = @include substr($tmp, 0, ($i + 1))."/main.inc.php";
}
if (!$res && $i > 0 && file_exists(dirname(substr($tmp, 0, ($i + 1)))."/main.inc.php")) {
	$res = @include dirname(substr($tmp, 0, ($i + 1)))."/main.inc.php";
}
// Try main.inc.php using relative path
if (!$res && file_exists("../main.inc.php")) {
	$res = @include "../main.inc.php";
}
if (!$res && file_exists("../../main.inc.php")) {
	$res = @include "../../main.inc.php";
}
if (!$res && file_exists("../../../main.inc.php")) {
	$res = @include "../../../main.inc.php";
}
if (!$res) {
	die("Include of main fails");
}

require_once DOL_DOCUMENT_ROOT.'/core/class/html.formcompany.class.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/date.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/company.lib.php';
require_once DOL_DOCUMENT_ROOT.'/custom/creche/class/enfants.class.php';
require_once DOL_DOCUMENT_ROOT.'/custom/creche/lib/creche_enfants.lib.php';
require_once DOL_DOCUMENT_ROOT.'/custom/creche/core/modules/creche/doc/pdf_contrats.php';

// load module libraries
require_once __DIR__.'/class/contrats.class.php';

// for other modules
//dol_include_once('/othermodule/class/otherobject.class.php');

// Load translation files required by the page
$langs->loadLangs(array("creche@creche", "other"));

// Get parameters
$action     = GETPOST('action', 'aZ09') ? GETPOST('action', 'aZ09') : 'view'; // The action 'create'/'add', 'edit'/'update', 'view', ...
$massaction = GETPOST('massaction', 'alpha'); // The bulk action (combo box choice into lists)
$show_files = GETPOST('show_files', 'int'); // Show files area generated by bulk actions ?
$confirm    = GETPOST('confirm', 'alpha'); // Result of a confirmation
$cancel     = GETPOST('cancel', 'alpha'); // We click on a Cancel button
$toselect   = GETPOST('toselect', 'array'); // Array of ids of elements selected into a list
$contextpage = GETPOST('contextpage', 'aZ') ? GETPOST('contextpage', 'aZ') : str_replace('_', '', basename(dirname(__FILE__)).basename(__FILE__, '.php')); // To manage different context of search
$backtopage = GETPOST('backtopage', 'alpha'); // Go back to a dedicated page
$optioncss  = GETPOST('optioncss', 'aZ'); // Option for the css output (always '' except when 'print')
$mode       = GETPOST('mode', 'aZ'); // The output mode ('list', 'kanban', 'hierarchy', 'calendar', ...)

$enfantid = GETPOST('idEnfant', 'int');


// Load variable for pagination
$limit = GETPOST('limit', 'int') ? GETPOST('limit', 'int') : $conf->liste_limit;
$sortfield = GETPOST('sortfield', 'aZ09comma');
$sortorder = GETPOST('sortorder', 'aZ09comma');
$page = GETPOSTISSET('pageplusone') ? (GETPOST('pageplusone') - 1) : GETPOST("page", 'int');
if (empty($page) || $page < 0 || GETPOST('button_search', 'alpha') || GETPOST('button_removefilter', 'alpha')) {
	// If $page is not defined, or '' or -1 or if we click on clear filters
	$page = 0;
}
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;

// Initialize technical objects
$enfant = new Enfants($db);
$enfant->fetch($enfantid);
// $object = new Contrats($db);
$diroutputmassaction = $conf->creche->dir_output.'/temp/massgeneration/'.$user->id;
$hookmanager->initHooks(array('enfantscard')); 	// Note that conf->hooks_modules contains array of activated contexes

// There is several ways to check permission.
// Set $enablepermissioncheck to 1 to enable a minimum low level of checks
$enablepermissioncheck = 1;
if ($enablepermissioncheck) {
	$permissiontoread = $user->hasRight('creche', 'enfants', 'read');
	$permissiontoadd = $user->hasRight('creche', 'enfants', 'write');
	$permissiontodelete = $user->hasRight('creche', 'enfants', 'delete');
} else {
	$permissiontoread = 1;
	$permissiontoadd = 1;
	$permissiontodelete = 1;
}

// Security check (enable the most restrictive one)
if ($user->socid > 0) accessforbidden();
//if ($user->socid > 0) accessforbidden();
//$socid = 0; if ($user->socid > 0) $socid = $user->socid;
//$isdraft = (($object->status == $object::STATUS_DRAFT) ? 1 : 0);
//restrictedArea($user, $object->module, 0, $object->table_element, $object->element, 'fk_soc', 'rowid', $isdraft);
if (!isModEnabled("creche")) {
	accessforbidden('Module creche not enabled');
}
if (!$permissiontoread) accessforbidden();


/*
 * Actions
 */
if ($action == 'addVaccin') {
	$sql = "INSERT INTO " . $db->prefix() . "creche_vaccin (fk_enfants, fk_vaccins, " . GETPOST('injection') . ") 
	VALUES(" . $enfantid . ", " . GETPOST('fk_vaccins') . ", '" . GETPOST('date') . "') 
	ON DUPLICATE KEY UPDATE " . GETPOST('injection') . " = '" . GETPOST('date') . "'";
	$req = $db->query($sql);

	if ($req) {
		setEventMessage('Vaccin ajouté');
	}

	header('Location: enfant_medicale.php?idEnfant=' . $enfantid);
	exit;
} elseif ($action == 'addPoids') {
	$sql = "INSERT INTO " . $db->prefix() . "creche_infos_medicale (fk_enfants, poids, date_poids) 
	VALUES(" . $enfantid . ", " . GETPOST('poids') . ", '" . GETPOST('date_poids') . "') 
	ON DUPLICATE KEY UPDATE poids = " . GETPOST('poids') . ", date_poids = '" . GETPOST('date_poids') . "'";
	$req = $db->query($sql);

	if ($req) {
		setEventMessage('Poids enregistré');
	}

	header('Location: enfant_medicale.php?idEnfant=' . $enfantid);
	exit;
} elseif ($action == 'addMedecin') {
	$sql = "INSERT INTO " . $db->prefix() . "creche_infos_medicale (fk_enfants, medecin_traitant, tel_medecin) 
	VALUES(" . $enfantid . ", '" . GETPOST('medecin_traitant') . "', '" . GETPOST('tel_medecin') . "') 
	ON DUPLICATE KEY UPDATE medecin_traitant = '" . GETPOST('medecin_traitant') . "', tel_medecin = '" . GETPOST('tel_medecin') . "'";
	$req = $db->query($sql);

	if ($req) {
		setEventMessage('Médecin enregistré');
	}

	header('Location: enfant_medicale.php?idEnfant=' . $enfantid);
	exit;
} elseif ($action == 'addAallergies') {
	$sql = "SELECT * 
	FROM " . $db->prefix() . "creche_infos_medicale 
	WHERE fk_enfants = " . $enfantid;
	$req = $db->query($sql);
	if ($db->num_rows($req) > 0) {
		$res = $db->fetch_object($req);
		$allergies = explode(';', $res->allergies);
		$allergies[] = GETPOST('allergies');
		$allergies = array_filter($allergies);
		$sql = "UPDATE " . $db->prefix() . "creche_infos_medicale SET allergies = '" . implode(';', $allergies) . "'";
	} else {
		$sql = "INSERT INTO " . $db->prefix() . "creche_infos_medicale (fk_enfants, allergies) 
		VALUES(" . $enfantid . ", '" . GETPOST('allergies') . "')";
	}
	$req = $db->query($sql);

	if ($req) {
		setEventMessage('Allergie enregistrée');
	}

	header('Location: enfant_medicale.php?idEnfant=' . $enfantid);
	exit;
} 




/*
 * View
 */

$form = new Form($db);

$now = dol_now();

$title = $langs->trans("Infos médicales");
//$help_url = "EN:Module_Contrats|FR:Module_Contrats_FR|ES:Módulo_Contrats";
$help_url = '';


// Output page
// --------------------------------------------------------------------
$title = $langs->trans("Enfants")." - ".$langs->trans('Infos médicales');
$help_url = '';

llxHeader('', $title, $help_url);

$head = enfantsPrepareHead($enfant);
print dol_get_fiche_head($head, 'medic', $langs->trans("Enfants"), -1, $enfant->picto, 0, '', '', 0, '', 1);

$linkback = '<a href="'.dol_buildpath('/creche/famille_enfants.php', 1).'?id=' . $enfant->fk_famille . '">'.$langs->trans("Retour à la famille").'</a>';

$sql = "SELECT fk_vaccins, label, date_1_injection, date_1_rappel, date_2_rappel 
		FROM " . $db->prefix() . "creche_vaccin AS v 
		INNER JOIN " . $db->prefix() . "c_crechevaccins AS dico ON dico.rowid = v.fk_vaccins 
		WHERE v.fk_enfants = " . $enfantid;
$reqVaccin = $db->query($sql);
$vaccins = array();
while ($vac = $db->fetch_object($reqVaccin)) {
	$vaccins[$vac->fk_vaccins] = $vac;
}

$sql = "SELECT * 
		FROM " . $db->prefix() . "c_crechevaccins 
		WHERE active = 1";
$reqVaccinType = $db->query($sql);
$vaccinType = array();
while ($vac = $db->fetch_object($reqVaccinType)) {
	$vaccinType[$vac->rowid] = $vac;
}

$sql = "SELECT * 
		FROM " . $db->prefix() . "creche_infos_medicale 
		WHERE fk_enfants = " . $enfantid;
$reqMedicale = $db->query($sql);
$nbRows = $db->num_rows($reqMedicale);
if ($nbRows > 0) {
	$resMedicale = $db->fetch_object($reqMedicale);
	$allergies = explode(';', $resMedicale->allergies);
}


dol_banner_tab($enfant, 'ref', $linkback, 1, 'ref', 'prenom', $morehtmlref);

// echo '<pre>';var_dump();echo '</pre>';
?>
<link href="css/creche.css" type="text/css" rel="stylesheet">
<div class="fichecenter">
		<div class="underbanner clearboth"></div>
		<h3>Vaccins</h3>
		<form method="post">
			<input type="hidden" name="idEnfant" value="<?= $enfantid ?>">
			<input type="hidden" name="token" value="<?= newToken() ?>">
			<input type="hidden" name="action" value="addVaccin">
			<table>
				<tr class="liste_titre">
					<td class="wrapcolumntitle liste_titre">Vaccin</td>
					<td class="wrapcolumntitle liste_titre">Injection</td>
					<td class="wrapcolumntitle liste_titre">Date</td>
				</tr>
				<tr>
					<td class="addFormTable">
						<select name="fk_vaccins" required>
							<option value="">Choisir un vaccin</option>
							<?php foreach ($vaccinType as $vac): ?>
								<option value="<?= $vac->rowid ?>"><?= $vac->label ?></option>
							<?php endforeach; ?>
						</select>
					</td>
					<td class="addFormTable">
						<select name="injection" required>
							<option value="">Choisir une injection</option>
							<option value="date_1_injection">1ère injection</option>
							<option value="date_1_rappel">1er rappel</option>
							<option value="date_2_rappel">2ème rappel</option>
						</select>
					</td>
					<td class="addFormTable"><input type="date" name="date" required></td>
					<td rowspan="2" class="addFormTable"><input type="submit" value="Enregistrer" class="button" ></td>
				</tr>
			</table>
		</form><br /><br />
		
		<table class="tagtable liste">
			<thead>
				<tr class="liste_titre">
					<th class="wrapcolumntitle liste_titre"><?= $langs->trans("Vaccins") ?></th>
					<th class="wrapcolumntitle liste_titre"><?= $langs->trans("1ère injection") ?></th>
					<th class="wrapcolumntitle liste_titre"><?= $langs->trans("1er rappel") ?></th>
					<th class="wrapcolumntitle liste_titre"><?= $langs->trans("2ème rappel") ?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($vaccinType as $res): 
					$date_1_injection = null;
					$date_1_rappel = null;
					$date_2_rappel = null;
					if ($vaccins[$res->rowid]->date_1_injection != null) {
						$date_1_injection = new DateTime($vaccins[$res->rowid]->date_1_injection);
					}
					if ($vaccins[$res->rowid]->date_1_rappel != null) {
						$date_1_rappel = new DateTime($vaccins[$res->rowid]->date_1_rappel);
					}
					if ($vaccins[$res->rowid]->date_2_rappel != null) {
						$date_2_rappel = new DateTime($vaccins[$res->rowid]->date_2_rappel);
					}
					?>
					<tr>
						<td>
							<?= $res->label ?>
						</td>
						<td>
							<?= $res->injection_1 == 0 ? 'X' : 
							($date_1_injection == null ? '00/00/0000' : $date_1_injection->format('d/m/Y')) ?>
						</td>
						<td>
							<?= $res->rappel_1 == 0 ? 'X' : 
							($date_1_rappel == null ? '00/00/0000' : $date_1_rappel->format('d/m/Y')) ?>
						</td>
						<td>
							<?= $res->rappel_2 == 0 ? 'X' : 
							($date_2_rappel == null ? '00/00/0000' : $date_2_rappel->format('d/m/Y')) ?>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table><br /><br />

		<h3>Autres Infos</h3>
		<!-- Ajout/Modif du poids de l'enfant -->
		<form method="post" id="weightForm">
			<input type="hidden" name="idEnfant" value="<?= $enfantid ?>">
			<input type="hidden" name="token" value="<?= newToken() ?>">
			<input type="hidden" name="action" value="addPoids">
			<table>
				<tr class="liste_titre">
					<td class="wrapcolumntitle liste_titre">Poids</td>
					<td class="wrapcolumntitle liste_titre">Date</td>
				</tr>
				<tr>
					<td class="addFormTable"><input type="number" name="poids" required></td>
					<td class="addFormTable"><input type="date" name="date_poids" required></td>
					<td rowspan="2" class="addFormTable"><input type="submit" value="Enregistrer" class="button" ></td>
				</tr>
			</table>
		</form>
		
		<!-- Ajout du médecin traitant de l'enfant -->
		<form method="post" id="doctorForm">
			<input type="hidden" name="idEnfant" value="<?= $enfantid ?>">
			<input type="hidden" name="token" value="<?= newToken() ?>">
			<input type="hidden" name="action" value="addMedecin">
			<table>
				<tr class="liste_titre">
					<td class="wrapcolumntitle liste_titre">Médecin</td>
					<td class="wrapcolumntitle liste_titre">Téléphone</td>
				</tr>
				<tr>
					<td class="addFormTable"><input type="text" name="medecin_traitant" required></td>
					<td class="addFormTable"><input type="tel" name="tel_medecin" required></td>
					<td rowspan="2" class="addFormTable"><input type="submit" value="Enregistrer" class="button" ></td>
				</tr>
			</table>
		</form>

		<form method="post" id="allergyForm">
			<input type="hidden" name="idEnfant" value="<?= $enfantid ?>">
			<input type="hidden" name="token" value="<?= newToken() ?>">
			<input type="hidden" name="action" value="addAallergies">
			<table>
				<tr class="liste_titre">
					<td class="wrapcolumntitle liste_titre">Allergie</td>
				</tr>
				<tr>
					<td class="addFormTable">
						<input type="text" name="allergies" required>
					</td>
					<td rowspan="2" class="addFormTable"><input type="submit" value="Ajout 1 allergie" class="button" ></td>
				</tr>
			</table>
		</form><br /><br />

		<table class="tagtable liste">
			<tbody>
				<tr>
					<td class="textBold"><?= $langs->trans("Poids") ?></td>
					<td>
						<?php if ($nbRows > 0 && $resMedicale->poids != null && $resMedicale->date_poids != null): ?>
							<?= $resMedicale->poids ?> kg au <?= $resMedicale->date_poids ?>
						<?php endif; ?>
					</td>
					<td>
						<button class="button btn_update" onclick="document.getElementById('weightForm').style.display = 'block';">
							<?= $langs->trans("Modifier") ?>
						</button>
					</td>
				</tr>
				<tr>
					<td class="textBold"><?= $langs->trans("Médecin traitant") ?></td>
					<td>
						<?php if ($nbRows > 0 && $resMedicale->medecin_traitant != null && $resMedicale->tel_medecin != null): ?>
							<?= $resMedicale->medecin_traitant ?><br />
							<span class="fas fa-phone pictofixedwidth" style=""></span> <?= $resMedicale->tel_medecin ?>
						<?php endif; ?>
					</td>
					<td>
						<button class="button btn_update" onclick="document.getElementById('doctorForm').style.display = 'block';">
							<?= $langs->trans("Modifier") ?>
						</button>
					</td>
				</tr>
				<tr>
					<td class="textBold"><?= $langs->trans("Allergies") ?></td>
					<td>
						<?php if ($nbRows > 0): ?>
							<?= implode("<br />", $allergies) ?>
						<?php endif; ?>
					</td>
					<td>
						<button class="button btn_update" onclick="document.getElementById('allergyForm').style.display = 'block';">
							<?= $langs->trans("Modifier") ?>
						</button>
					</td>
				</tr>
			</tbody>
		</table>
</div>

<?php
llxFooter();
$db->close();
