<?php
// Load Dolibarr environment
$res = 0;
// Try main.inc.php into web root known defined into CONTEXT_DOCUMENT_ROOT (not always defined)
if (!$res && !empty($_SERVER["CONTEXT_DOCUMENT_ROOT"])) {
	$res = @include $_SERVER["CONTEXT_DOCUMENT_ROOT"]."/main.inc.php";
}
// Try main.inc.php into web root detected using web root calculated from SCRIPT_FILENAME
$tmp = empty($_SERVER['SCRIPT_FILENAME']) ? '' : $_SERVER['SCRIPT_FILENAME']; $tmp2 = realpath(__FILE__); $i = strlen($tmp) - 1; $j = strlen($tmp2) - 1;
while ($i > 0 && $j > 0 && isset($tmp[$i]) && isset($tmp2[$j]) && $tmp[$i] == $tmp2[$j]) {
	$i--;
	$j--;
}
if (!$res && $i > 0 && file_exists(substr($tmp, 0, ($i + 1))."/main.inc.php")) {
	$res = @include substr($tmp, 0, ($i + 1))."/main.inc.php";
}
if (!$res && $i > 0 && file_exists(dirname(substr($tmp, 0, ($i + 1)))."/main.inc.php")) {
	$res = @include dirname(substr($tmp, 0, ($i + 1)))."/main.inc.php";
}
// Try main.inc.php using relative path
if (!$res && file_exists("../main.inc.php")) {
	$res = @include "../main.inc.php";
}
if (!$res && file_exists("../../main.inc.php")) {
	$res = @include "../../main.inc.php";
}
if (!$res && file_exists("../../../main.inc.php")) {
	$res = @include "../../../main.inc.php";
}
if (!$res) {
	die("Include of main fails");
}

require_once DOL_DOCUMENT_ROOT.'/core/class/html.formcompany.class.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/date.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/company.lib.php';
require_once DOL_DOCUMENT_ROOT.'/custom/creche/class/enfants.class.php';
require_once DOL_DOCUMENT_ROOT.'/custom/creche/lib/creche_enfants.lib.php';
require_once DOL_DOCUMENT_ROOT.'/custom/creche/core/modules/creche/doc/pdf_contrats.php';

// load module libraries
require_once __DIR__.'/class/contrats.class.php';

// for other modules
//dol_include_once('/othermodule/class/otherobject.class.php');

// Load translation files required by the page
$langs->loadLangs(array("creche@creche", "other"));

// Get parameters
$action     = GETPOST('action', 'aZ09') ? GETPOST('action', 'aZ09') : 'view'; // The action 'create'/'add', 'edit'/'update', 'view', ...
$massaction = GETPOST('massaction', 'alpha'); // The bulk action (combo box choice into lists)
$show_files = GETPOST('show_files', 'int'); // Show files area generated by bulk actions ?
$confirm    = GETPOST('confirm', 'alpha'); // Result of a confirmation
$cancel     = GETPOST('cancel', 'alpha'); // We click on a Cancel button
$toselect   = GETPOST('toselect', 'array'); // Array of ids of elements selected into a list
$contextpage = GETPOST('contextpage', 'aZ') ? GETPOST('contextpage', 'aZ') : str_replace('_', '', basename(dirname(__FILE__)).basename(__FILE__, '.php')); // To manage different context of search
$backtopage = GETPOST('backtopage', 'alpha'); // Go back to a dedicated page
$optioncss  = GETPOST('optioncss', 'aZ'); // Option for the css output (always '' except when 'print')
$mode       = GETPOST('mode', 'aZ'); // The output mode ('list', 'kanban', 'hierarchy', 'calendar', ...)

$enfantid = GETPOST('idEnfant', 'int');


// Load variable for pagination
$limit = GETPOST('limit', 'int') ? GETPOST('limit', 'int') : $conf->liste_limit;
$sortfield = GETPOST('sortfield', 'aZ09comma');
$sortorder = GETPOST('sortorder', 'aZ09comma');
$page = GETPOSTISSET('pageplusone') ? (GETPOST('pageplusone') - 1) : GETPOST("page", 'int');
if (empty($page) || $page < 0 || GETPOST('button_search', 'alpha') || GETPOST('button_removefilter', 'alpha')) {
	// If $page is not defined, or '' or -1 or if we click on clear filters
	$page = 0;
}
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;

// Initialize technical objects
$enfant = new Enfants($db);
$enfant->fetch($enfantid);
// $object = new Contrats($db);
$diroutputmassaction = $conf->creche->dir_output.'/temp/massgeneration/'.$user->id;
$hookmanager->initHooks(array('enfantscard')); 	// Note that conf->hooks_modules contains array of activated contexes

// There is several ways to check permission.
// Set $enablepermissioncheck to 1 to enable a minimum low level of checks
$enablepermissioncheck = 1;
if ($enablepermissioncheck) {
	$permissiontoread = $user->hasRight('creche', 'enfants', 'read');
	$permissiontoadd = $user->hasRight('creche', 'enfants', 'write');
	$permissiontodelete = $user->hasRight('creche', 'enfants', 'delete');
} else {
	$permissiontoread = 1;
	$permissiontoadd = 1;
	$permissiontodelete = 1;
}

// Security check (enable the most restrictive one)
if ($user->socid > 0) accessforbidden();
//if ($user->socid > 0) accessforbidden();
//$socid = 0; if ($user->socid > 0) $socid = $user->socid;
//$isdraft = (($object->status == $object::STATUS_DRAFT) ? 1 : 0);
//restrictedArea($user, $object->module, 0, $object->table_element, $object->element, 'fk_soc', 'rowid', $isdraft);
if (!isModEnabled("creche")) {
	accessforbidden('Module creche not enabled');
}
if (!$permissiontoread) accessforbidden();


/*
 * Actions
 */
if ($action == 'add') {
	$sql = "INSERT INTO " . $db->prefix() . "creche_infos_divers (fk_enfants, label, `date`) 
	VALUES (" . $enfantid . ", '" . GETPOST('label') . "', '" . GETPOST('date') . "')";
	$req = $db->query($sql);

	if ($req) {
		setEventMessage('Information ajoutée');
	}

	header('Location: enfant_divers.php?idEnfant=' . $enfantid);
	exit;
}




/*
 * View
 */

$form = new Form($db);

$now = dol_now();

$title = $langs->trans("Infos diverses");
//$help_url = "EN:Module_Contrats|FR:Module_Contrats_FR|ES:Módulo_Contrats";
$help_url = '';


// Output page
// --------------------------------------------------------------------
$title = $langs->trans("Enfants")." - ".$langs->trans('Infos diverses');
$help_url = '';

llxHeader('', $title, $help_url);

$head = enfantsPrepareHead($enfant);
print dol_get_fiche_head($head, 'divers', $langs->trans("Enfants"), -1, $enfant->picto, 0, '', '', 0, '', 1);

$linkback = '<a href="'.dol_buildpath('/creche/famille_enfants.php', 1).'?id=' . $enfant->fk_famille . '">'.$langs->trans("Retour à la famille").'</a>';

$sql = "SELECT * 
		FROM " . $db->prefix() . "creche_infos_divers 
		WHERE fk_enfants = " . $enfantid . "
		ORDER BY date DESC";
$req = $db->query($sql);

dol_banner_tab($enfant, 'ref', $linkback, 1, 'ref', 'prenom', $morehtmlref);

// echo '<pre>';var_dump();echo '</pre>';
?>
<link href="css/creche.css" type="text/css" rel="stylesheet">
<div class="fichecenter">
		<div class="underbanner clearboth"></div>
		<form method="post">
			<input type="hidden" name="idEnfant" value="<?= $enfantid ?>">
			<input type="hidden" name="token" value="<?= newToken() ?>">
			<input type="hidden" name="action" value="add">
			<table>
				<tr class="liste_titre">
					<td class="wrapcolumntitle liste_titre">Description</td>
					<td class="wrapcolumntitle liste_titre">Date</td>
				</tr>
				<tr>
					<td class="addFormTable"><input type="text" name="label"></td>
					<td class="addFormTable"><input type="date" name="date"></td>
					<td rowspan="2" class="addFormTable"><input type="submit" value="Ajouter" class="button" ></td>
				</tr>
			</table>
		</form><br /><br />
		
		<table class="tagtable liste">
			<thead>
				<tr class="liste_titre">
					<th class="wrapcolumntitle liste_titre"><?= $langs->trans("Description") ?></th>
					<th class="wrapcolumntitle liste_titre"><?= $langs->trans("Date") ?></th>
				</tr>
			</thead>
			<tbody>
				<?php while ($res = $db->fetch_object($req)): 
					$date = new DateTime($res->date); ?>
					<tr>
						<td>
							<?= $res->label ?>
						</td>
						<td>
							<?= $date->format('d/m/Y') ?>
						</td>
					</tr>
				<?php endwhile; ?>
			</tbody>
		</table>
	</div>

<?php
llxFooter();
$db->close();
